### ISSUE TITLE
Build failed in macos Mojave

### ISSUE THREAD

**Issue by SeavantUUz** [dexon-foundation/dexon#139]
Follow the steps in [Installation Instructions](https://github.com/dexon-foundation/wiki/wiki/Installation-Instructions-for-Mac) could not build gdex successfully in Mojave( or neither older version I do not know).

I noticed some description is not correct in the wiki:
```
brew install gmp libssl
```

No, there isn't a package called libssl for me or for the latest version of homebrew. I replaced it by `brew install openssl` and set bash env like `export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"` as pkg_config could find the *libcrypto* library.

> If you see some errors related to header files of Mac OS system library, install XCode Command Line Tools, and try again.

Just reinstall Command Line Tools could not avoid error messages raised by `github.com/rjeczalik/notify`:
```
In file included from vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:10:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /Library/Frameworks/AE.framework/Headers/AE.h:29:
/Library/Frameworks/AE.framework/Headers/AppleEvents.h:597:165: error: expected function body after function declarator
extern OSStatus AEDeterminePermissionToAutomateTarget( const AEAddressDesc* target, AEEventClass theAEEventClass, AEEventID theAEEventID, Boolean askUserIfNeeded ) __OSX_AVAILABLE_STARTING( __MAC_10_14, __IPHONE_NA );
                                                                                                                                                                    ^
/usr/include/Availability.h:216:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:46:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_14
^
1 error generated.
```

To solve the problem, I find [this](https://github.com/ethereum/go-ethereum/issues/17940) is useful and work.

**Comment by SeavantUUz** [comment]
Maybe you somehow have installed the sdk headers for macOS 14.

**Comment by SeavantUUz** [comment]
xcode: Version 10.1 (10B61)
xcode-select: version 2354

**Comment by jimmyhu-dexon** [comment]
Added to the instructions.
