### ISSUE TITLE
Can I run a private chain in local

### ISSUE THREAD

**Issue by SeavantUUz** [dexon-foundation/dexon#148]
As stated above, I wanna run a private chain in local.

Following the steps in readme, I created a `genesis.json` and try `gdex init genesis.json` it. Then I tried to run gdex but failed with error msgs like:

```
ERROR[01-14|15:44:19.721] Governance state incorrect               round=18446744073709551612 got height=0
panic: round != 0 but height == 0
```

Like the governance has not been configured correctly. Did I ignore something ? Or , how can I run it is just like your testnet? I tried to run a testnet in local without syncing the data from your testnet.

The branch I built from is branch dev.

Thx.

**Comment by jimmyhu-dexon** [comment]
go to `test` and run `./run_test.sh --local`
